apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: Helm
    app: studentx
    tier: frontend
spec:
  ports:
    - port: 3000
  selector:
    app: studentx
    tier: frontend
  clusterIP: None # Headless service
