apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - {{ required ".Values.ingress.name entry is required!" .Values.ingress.name }}
    secretName: {{ regexReplaceAll "\\." .Values.ingress.name "" }}-tls
  rules:
  # host rule will route traffic when the hostname requested matches
  - host: {{ required ".Values.ingress.name entry is required!" .Values.ingress.name }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: svc-backend
            port:
              number: 5000
