apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: Helm
    app: studentx
    tier: backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
  selector:
    app: studentx
    tier: backend
