apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monapp
  namespace: <prenom>-test3
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "formk8s"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    cert-manager.io/issuer: "issuer-letsencrypt-prod"
spec:
  tls:
  - hosts:
    - mondomaine.com
    secretName: my-letsencrypt-certificate
  rules:
  - host: mondomaine.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-frontend-clusterip
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: service-api-clusterip
            port:
              number: 8080

