kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: <prenom>-test3
  name: api-allow-all
spec:
  podSelector:
    matchLabels:
      app: monapp
      tier: api
  ingress:
  - {}
